### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wxlg1117** [rshipp/webNUT#2]
DietPi with nut-server=2.7.4

wget https://bootstrap.pypa.io/ez_setup.py
wget https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
python ez_setup.py
git clone https://github.com/rshipp/webNUT.git
cd webNUT
vim  webNUT/webnut/config.py
python setup.py build
python setup.py install

then:
pserve development.ini

**get some errer**:
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 11, in <module>
    load_entry_point('pyramid==1.9.2', 'console_scripts', 'pserve')()
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy-0.6-py2.7.egg/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/webNUT-0.0-py2.7.egg/webnut/__init__.py", line 15, in main
    context='pyramid.exceptions.NotFound')
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/util.py", line 540, in wrapper
    view = self.maybe_dotted(view)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 912, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/local/lib/python2.7/dist-packages/pyramid-1.9.2-py2.7.egg/pyramid/path.py", line 382, in _zope_dottedname_style
    __import__(used)
  File "/usr/local/lib/python2.7/dist-packages/webNUT-0.0-py2.7.egg/webnut/views.py", line 6, in <module>
    import config
  File "/usr/local/lib/python2.7/dist-packages/webNUT-0.0-py2.7.egg/webnut/config.py", line 6
    password = removed
                      ^
SyntaxError: invalid syntax

how can i do ?

**Comment by rshipp** [comment]
Hi! Looks like you just need to put your password in quotes in `webNUT/webnut/config.py`. 

    password = "your password here"

**Comment by wxlg1117** [comment]
password i set already, when i paste in issue ,removed by github system

**Comment by rshipp** [comment]
I edited your comment to remove the password. If you check config.py, you will see your password without quotes. Just put it inside quotes and you're good to go.

**Comment by wxlg1117** [comment]
config.py with :
server = '127.0.0.1'
port = 3493
username = 'upsmon'
password = 'password'

and same error when i start it...

**Comment by rshipp** [comment]
Please double check you are editing the correct file: 

    /usr/local/lib/python2.7/dist-packages/webNUT-0.0-py2.7.egg/webnut/config.py

**Comment by rshipp** [comment]
Glad that solved it. Hope the tool is useful for you.
