### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by carsonl** [rshipp/webNUT#3]
As Python 2 has been deprecated, are there any plans for Python 3 support?

**Comment by rshipp** [comment]
I haven't used this in a long time. Is something broken on Python 3? If you do a PR I'm happy to take a look.

**Comment by carsonl** [comment]
I don't really know what I'm doing, but I tried to install this in a container using Ubuntu 20.04 as a base image, and I couldn't get it running... it could just be user error, and using the correct packages/commands could solve it... 

I think it is related to changes made to pyramid for Python 3.

Basically, I'm using a base ubuntu 20.04, running:
```
apt-get --no-install-recommends -y install ca-certificates python3-pyramid
cd /webNUT/ #A clone of webnut/ from this repo
python3 setup.py install
pserve3 production.ini
```

The error I'm getting:
```
root@aa14f2b66455:/webNUT# pserve3 production.ini
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyramid/path.py", line 395, in _zope_dottedname_style
    found = getattr(found, n)
AttributeError: module 'webnut' has no attribute 'views'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pserve3", line 11, in <module>
    load_entry_point('pyramid==1.10.4', 'console_scripts', 'pserve')()
  File "/usr/lib/python3/dist-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "/usr/lib/python3/dist-packages/pyramid/scripts/pserve.py", line 275, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/lib/python3/dist-packages/plaster_pastedeploy/__init__.py", line 128, in get_wsgi_app
    return loadapp(self.pastedeploy_spec,
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python3/dist-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python3/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/webNUT-0.0-py3.8.egg/webnut/__init__.py", line 13, in main
    config.add_view('webnut.views.notfound',
  File "/usr/lib/python3/dist-packages/pyramid/config/views.py", line 235, in wrapper
    view = self.maybe_dotted(view)
  File "/usr/lib/python3/dist-packages/pyramid/config/__init__.py", line 749, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/usr/lib/python3/dist-packages/pyramid/path.py", line 335, in maybe_resolve
    return self._resolve(dotted, package)
  File "/usr/lib/python3/dist-packages/pyramid/path.py", line 342, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/lib/python3/dist-packages/pyramid/path.py", line 397, in _zope_dottedname_style
    __import__(used)
  File "/usr/local/lib/python3.8/dist-packages/webNUT-0.0-py3.8.egg/webnut/views.py", line 5, in <module>
    from webnut import WebNUT
ImportError: cannot import name 'WebNUT' from 'webnut' (/usr/local/lib/python3.8/dist-packages/webNUT-0.0-py3.8.egg/webnut/__init__.py)
```

**Comment by rshipp** [comment]
Thanks for the details, it should be fixed now.
